### ISSUE TITLE
Eclipse 4.2/4.5 - samples-desktop - Run As - SwingCanvasSample

### ISSUE THREAD

**Issue by nicofr69** [siondream/libgdx-cookbook#10]
Hello,
I checkout the "cookbook-1.3.0" tag into Eclipse, gradle-build, and run using "Run As > Java Application > SwingCanvasSample". The sampler launches, but the individual sample programs are crashing, e.g. SpriteSample.
I don't encounter this problem neither with Main.java, not with /environment wihch just work fine.

On Eclipse 4.2 Juno, I get the error message
AL lib: (EE) DoReset: Failed to initialize audio client: 0x88890017
Exception in thread "AWT-EventQueue-0" org.lwjgl.openal.OpenALException: Invalid Device
    at org.lwjgl.openal.Util.checkALCError(Util.java:55)
...
On Eclipse 4.5 Mars, I get the error message
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at com.cookbook.samples.SpriteSample.dispose(SpriteSample.java:73)
...
and on second execution the error message
Exception in thread "AWT-EventQueue-0" com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 3.1.0 - Build 9.17.10.4229
Intel
Intel(R) HD Graphics 3000
3.1.0 - Build 9.17.10.4229
    at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.create(LwjglAWTCanvas.java:222)
...
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 3.1.0 - Build 9.17.10.4229
Intel
Intel(R) HD Graphics 3000
3.1.0 - Build 9.17.10.4229
    at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGLInstances(LwjglGraphics.java:316)
    at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.create(LwjglAWTCanvas.java:214)
    ... 25 more
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.render(LwjglAWTCanvas.java:238)
...
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Thanks for any hint to solve this issue,
NIkolas

**Comment by dsaltares** [comment]
I was just able to reproduce the issue and will look into fixing it. As a workaround, for the time being, could you work with [cookbook-1.2.0](https://github.com/saltares/libgdx-cookbook/releases/tag/cookbook-1.2.0)?

**Comment by dsaltares** [comment]
It seems that `extractVersion()` in `LwjglGraphics.java` is not being called, so Libgdx thinks the available OpenGL version is 0, which is obviously wrong. Will keep investigating.

**Comment by AlbertoCejas** [comment]
Switching from LwjglAWTCanvas to LwjglCanvas fixes the issue.

nicofr69, thanks for reporting

**Comment by sutchark** [comment]
Strange, LwjglAWTCanvas works fine for me after I changed it from LwjglCanvas.

I did this because LwjglCanvas has a different problem. The first sample you launch always works fine. Launching the second sample however leads to an exception. I guess this is a problem with stop() or remove() or something. There seems to be some leftover LwglCanvas state that collides with creating a new LwglCanvas.

Here is the exception:
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Only one OpenAL context may be instantiated at any one time.
	at org.lwjgl.openal.AL.create(AL.java:113)
	at org.lwjgl.openal.AL.create(AL.java:102)
	at org.lwjgl.openal.AL.create(AL.java:206)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.<init>(OpenALAudio.java:72)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.<init>(OpenALAudio.java:57)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.initialize(LwjglCanvas.java:122)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.<init>(LwjglCanvas.java:66)
	at com.cookbook.samples.desktop.SwingCanvasSample.launchSample(SwingCanvasSample.java:54)
	at com.cookbook.samples.desktop.SampleList$3.actionPerformed(SampleList.java:69)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.cookbook.samples.desktop.SampleList$1.mouseClicked(SampleList.java:49)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
	at java.awt.Container.dispatchEventImpl(Container.java:2282)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
org.lwjgl.LWJGLException: X Error - disp: 0x7fd534386aa0 serial: 946 error: BadDrawable (invalid Pixmap or Window parameter) request_code: 154 minor_code: 7
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.GL11.nglClear(Native Method)
	at org.lwjgl.opengl.GL11.glClear(GL11.java:588)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glClear(LwjglGL20.java:151)
	at com.cookbook.samples.ShaderSample.render(ShaderSample.java:82)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:240)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL20.glUseProgram(GL20.java:295)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glUseProgram(LwjglGL20.java:769)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.dispose(ShaderProgram.java:683)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.dispose(SpriteBatch.java:1011)
	at com.cookbook.samples.ShaderSample.dispose(ShaderSample.java:69)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:309)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
